apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label2
  labels:
    team: rnd
    version: 0.1.0
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80